#!/bin/bash
FILE="data.json"
name=$(jq -r '.name' "$FILE")
height=$(jq -r '.height' "$FILE")
weight=$(jq -r '.weight' "$FILE")
type=$(jq -r '.types[0].type.name' "$FILE")
echo "${name^} is of type ${type^}, weighs ${weight}kg, and is ${height}m tall."
